version: "3"

services:
  gateway_api:
    build: ./APIs/api_gateway/.
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/breakdown/api_gateway
    depends_on:
      - commit_api
      - issue_api
      - pullrequest_api
      - branch_api
      - ranking_api
      - profile_api

    links:
      - commit_api
      - issue_api
      - pullrequest_api
      - branch_api
      - ranking_api
      - profile_api
  
  commit_api:
    build: ./APIs/commits_request/.
    command: npm start
    ports:
      - "3001:3001"
    volumes:
      - .:/usr/breakdown/commits_request
  
  issue_api:
    build: ./APIs/issues_request/.
    command: npm start
    ports:
      - "3002:3002"
    volumes:
      - .:/usr/breakdown/issues_request
  
  pullrequest_api:
    build: ./APIs/pullrequests_request/.
    command: npm start
    ports:
      - "3003:3003"
    volumes:
      - .:/usr/breakdown/pullrequests_request

  branch_api:
    build: ./APIs/branches_request/.
    command: npm start
    ports:
      - "3004:3004"
    volumes:
      - .:/usr/breakdown/branches_request

  ranking_api:
    build: ./APIs/ranking_request/.
    command: npm start
    ports:
      - "3005:3005"
    volumes:
      - .:/usr/breakdown/ranking_request

  profile_api:
    build: ./APIs/profile_request/.
    command: npm start
    ports:
      - "3006:3006"
    volumes:
      - .:/usr/breakdown/profile_request

