version: "3"

services:
  commit_api:
    build: ./APIs/commit_request/.
    command: npm run dev
    ports:
      - "3001:3001"
    volumes:
      - .:/usr/breakdown/commit_request
  issue_api:
    build: ./APIs/issues_request/.
    command: npm start
    ports:
      - "3002:3002"
    volumes:
      - .:/usr/breakdown/issues_request
  pullrequest_api:
    build: ./APIs/pullrequests_request/.
    command: npm start
    ports:
      - "3003:3003"
    volumes:
      - .:/usr/breakdown/pullrequests_request